version: '3.8'

services:
  web:
    container_name: vora-web
    build: .
    restart: always
    ports:
      - "3005:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/vora?schema=public
      - NEXTAUTH_URL=https://vora.usev.app
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    depends_on:
      - db
    networks:
      - vora-network

  db:
    image: postgres:16-alpine
    container_name: vora-db-prod
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vora
    volumes:
      - vora_prod_data:/var/lib/postgresql/data
    networks:
      - vora-network

networks:
  vora-network:
    driver: bridge

volumes:
  vora_prod_data:
